
export const EVENT_LIST_REQUEST = 'EVENT_LIST_REQUEST'
export const EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS'
export const EVENT_LIST_FAIL = 'EVENT_LIST_FAIL'

export const EVENT_DETAILS_REQUEST = 'EVENT_DETAILS_REQUEST'
export const EVENT_DETAILS_SUCCESS = 'EVENT_DETAILS_SUCCESS'
export const EVENT_DETAILS_FAIL = 'EVENT_DETAILS_FAIL'



export const ADD_EVENT_REQUEST='ADD_EVENT_REQUEST'
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS'
export const CLEAR_EVENT  ='CLEAR_EVENT'

export const REMOVE_EVENT = 'REMOVE_EVENT'



export const MY_EVENTS_REQUEST='MY_EVENTS_REQUEST'
export const MY_EVENTS_SUCCESS = 'MY_EVENTS_SUCCESS'
